// Generated by argus_skill.release_tools.generate_manifest. Do not edit.
export const RELEASE_ID = "0.1.1+96e2ceb99ceb9203";
export const RELEASE_SOURCE_DIGEST = "96e2ceb99ceb92038a04e6df88407a596d8c7195f54c869b01c92ee1fc134caa";
