// Generated by argus_skill.release_tools.generate_manifest. Do not edit.
export const RELEASE_ID = "0.1.1+26943b1a0310b5b7";
export const RELEASE_SOURCE_DIGEST = "26943b1a0310b5b729d277cd66e5b071f0c28c622f07a7bfa830d89c1f8825ff";
