// Generated by argus_skill.release_tools.generate_manifest. Do not edit.
export const RELEASE_ID = "0.1.1+fcbb8f9084e1a8f6";
export const RELEASE_SOURCE_DIGEST = "fcbb8f9084e1a8f67bae58a8b88a3392bd5d15fa16f773c1af7283ab7735372b";
